### ISSUE TITLE
Unable to add user to group data access core

### ISSUE THREAD

**Issue by terjeasa** [dhis2/dhis2-trainingland#32]
With superuser rights I received the following error when I tried to create  a new user with membership in the group data access core: 
You don't have update access to object {"class":"class org.hisp.dhis.user.UserGroup", "id":"2865", "uid":"GtqOC9gyFMN", "code":"null", "name":"Data Access - Core", "created":"2015-10-15 13:26:23.122", "lastUpdated":"Thu Mar 31 11:28:47 UTC 2016" }

**Comment by olatitle** [comment]
I have now changed the sharing settings so that users that are members of the user group "Trainingland admins" have write access to the group "Data Access - Core".

We need to come up with a better approach as we want more users than the Trainingland admins to create academy participant accounts. Should check with Lars or Jim how the Pepfar system is setup.
